apiVersion: v2
name: nfs-external-provisioner
version: 4.4.3
appVersion: 1.4.0
dependencies:
- version: 4.4.3
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
type: application


