appVersion: 1.4.0
version: 4.4.2
apiVersion: v2
type: application
dependencies:
- version: 4.4.2
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
name: nfs-external-provisioner


