apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tap
spec:
  secretName: tap-k8s-tls
  duration: 24h0m0s
  renewBefore: 1h0m0s
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: tap.linkerd-viz.svc
  dnsNames:
  - tap.linkerd-viz.svc
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth