argo-cd:
  global:
    storageClass: nfs-client
    podAnnotations:
      linkerd.io/inject: enabled
  controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  repoServer:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  redis:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  applicationSet:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  notifications:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  server:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/service-upstream: "true"
        kubernetes.io/ingress.class: nginx
      hosts:
      - argo.mattgerega.net

    config:
      url: https://argo.mattgerega.net
      resource.customizations.ignoreDifferences.all: |
        managedFieldsManagers:
        - external-secrets
      dex.config: |
        logger:
          level: debug
          format: json
        connectors:
        - type: saml
          id: saml
          name: Azure AD
          config:
            entityIssuer: https://argo.mattgerega.net/api/dex/callback
            ssoURL: https://login.microsoftonline.com/70965cdd-c60c-4109-9fcf-709b2f23bd0c/saml2
            caData: $argo-azuread-secret:cert
            redirectURI: https://argo.mattgerega.net/api/dex/callback
            usernameAttr: email
            emailAttr: email
            groupsAttr: group
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        p, role:org-admin, applications, *, */*, allow
        p, role:org-admin, clusters, get, *, allow
        p, role:org-admin, repositories, get, *, allow
        p, role:org-admin, repositories, create, *, allow
        p, role:org-admin, repositories, update, *, allow
        p, role:org-admin, repositories, delete, *, allow
        g, "bad2673a-2a0e-46f0-ab2f-bfe0c9b67274", role:org-admin

  configs:
    params:
      server.insecure: true
      server.repo.server.strict.tls: false
      server.rootpath: ''
    repositories:
      argo-helm:
        url: https://argoproj.github.io/argo-helm
        name: argo-helm
        type: helm
      git-ops-nonprod-cluster:
        name: git-ops-nonprod-cluster
        url: https://bitbucket.org/spydersoftteam/ops-nonprod-cluster
        type: git
      git-ops-prod-cluster:
        name: git-ops-nonprod-cluster
        url: https://bitbucket.org/spydersoftteam/ops-nonprod-cluster
        type: git
    
