promtail:
  config:
    clients:
    - url: 'https://loki.mattgerega.net/loki/api/v1/push'
  serviceMonitor:
    enabled: true
    interval: 1m
    scrapeTimeout: 30s
  podAnnotations: 
      linkerd.io/inject: enabled
  snippets:
    pipelineStages:
      - match:
          selector: '{spydersoft.io/log="dotnet-serilog"}'
          stages:
          - json:
            expressions:
              message: '@mt'
              trace_id: TraceId
              span_id: SpanId
            timestamp:
              source: '"@t"'
              format: RFC3339
            labels:
              level:
                source: '"@l"'
              venue:
                source: "venueId"
              application:
                source: "Application"
            output:
              source: '{message: "@m", stack: "@x"}'
      - cri: {}
