promtail:
  config:
    clients:
    - url: 'https://loki.mattgerega.net/loki/api/v1/push'
  serviceMonitor:
    enabled: true
    interval: 1m
    scrapeTimeout: 30s
  podAnnotations: 
      linkerd.io/inject: enabled
  extraScrapeConfigs: |
    - job_name: system
      static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/logs/*.log
      pipeline_stages:
      - match:
         selector: '{spydersoft.io/log="dotnet-serilog"}'
        - json: 
            timestamp:
              source: '"@t"'
              format: RFC3339
            labels:
              level:
                source: '"@l"'
              venue:
                source: "venueId"
              application:
                source: "Application"
            output:
              source: '{message: "@m", stack: "@x"}'