promtail:
  config:
    clients:
      - url: "https://loki.mattgerega.net/loki/api/v1/push"
        external_labels:
          cluster: internal
    snippets:
      extraRelabelConfigs:
        - source_labels:
            - "__meta_kubernetes_pod_label_app_kubernetes_io_component"
          regex: "(canary|read|write)"
          action: "drop"
  service:
    labels:
      fix: "true"
    annotations:
      fix: "true"
