apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: linkerd-viz-tool
  labels:
    spydersoft.io/category: cluster-tools
spec:
  generators:
   - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
          spydersoft.io/linkerd-viz: 'true'
  template:
    metadata:
      name: '{{ nameNormalized }}-linkerd-viz'
      labels:
        spydersoft.io/category: cluster-tools 
    spec:
      project: cluster-tools
      source:
        repoURL: https://bitbucket.org/spydersoftteam/ops-argo
        targetRevision: main
        path: 'cluster-tools/tools/linkerd-viz'
        helm: 
          valueFiles:
            - 'config/{{name}}-values.yaml'
      destination:
        server: '{{ server }}'
        namespace: 'linkerd-viz'
      ignoreDifferences:
      - group: ""
        kind: Secret
        name:  tap-injector-k8s-tls
        jsonPointers:
        - /data/tls.crt
        - /data/tls.key
      - group: ""
        kind: Secret
        name:  tap-k8s-tls
        jsonPointers:
        - /data/tls.crt
        - /data/tls.key
      - group: admissionregistration.k8s.io/v1
        kind: MutatingWebhookConfiguration
        name: linkerd-tap-injector-webhook-config
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
      - group: admissionregistration.k8s.io/v1
        kind: ValidatingWebhookConfiguration
        name:  linkerd-sp-validator-webhook-config
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
      - group: apiregistration.k8s.io/v1
        kind: APIService
        name: v1alpha1.tap.linkerd.io
        jsonPointers:
        - /spec/caBundle
      syncPolicy:
        # automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
        #   prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
        #   selfHeal: false
        syncOptions:     # Sync options which modifies sync behavior
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
      