apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-dynamic-tool
  labels:
    spydersoft.io/category: cluster-tools
spec:
  goTemplate: true
  generators:
   - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
          spydersoft.io/test-dynamic: 'true'
  template:
    metadata:
      name: '{{ .nameNormalized }}-test-dynamic'
      labels:
        spydersoft.io/category: cluster-tools 
    spec:
      project: cluster-tools
      source:
        repoURL: https://bitbucket.org/spydersoftteam/ops-argo
        targetRevision: main
        path: 'cluster-tools/tools/test-dynamic'
        helm:
          parameters:
          {{- range $index, $element := splitList "_" .metadata.labels.loadBalancerIps}}
          - name: "externalIPs[$index]"
            value: '{{$element}}'
          {{- end}}
          
      destination:
        server: '{{ .server }}'
        namespace: 'cluster-tools'
      #syncPolicy:
        # automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
        #  prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
        #  selfHeal: false
      