kube-prometheus:
  prometheus:
    ingress:
      hostname: internal-cluster.mattgerega.net
    thanos:
      ingress:
        hostname: internal-cluster.mattgerega.net
    alertmanager:
      ingress:
        hostname: prod-cluster.mattgerega.net
    externalLabels:
      cluster: internal
    remoteWrite:
      - https://mimir.mattgerega.net/api/v1/push