kube-prometheus:
  prometheus:
    ingress:
      hostname: nonprod-cluster.mattgerega.net
    thanos:
      ingress:
        hostname: nonprod-cluster.mattgerega.net
    alertmanager:
      ingress:
        hostname: prod-cluster.mattgerega.net
    externalLabels:
      cluster: nonproduction