kube-prometheus:
  operator:
    logLevel: debug
  prometheus:
    logLevel: debug
    ingress:
      hostname: nonprod-cluster.mattgerega.net
    thanos:
      ingress:
        hostname: nonprod-cluster.mattgerega.net
    alertmanager:
      ingress:
        hostname: nonprod-cluster.mattgerega.net
    externalLabels:
      cluster: nonproduction