nonproduction_scrape_config:
  enabled: true
  name: production-scrape-config
kube-prometheus:
  prometheus:
    ingress:
      hostname: nonprod-cluster.mattgerega.net
    thanos:
      ingress:
        hostname: nonprod-cluster.mattgerega.net
    alertmanager:
      ingress:
        hostname: nonprod-cluster.mattgerega.net
    externalLabels:
      cluster: nonproduction