kube-prometheus:
  prometheus:
    thanos:
      create: true
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$2
        path: /thanos(/|$)(.*)
        enabled: true
        ingressClassName: nginx