kube-prometheus:
  prometheus:
    ingress:
      enabled: true
      ingressClassName: nginx
      path: /prometheus(/|$)(.*)
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
    thanos:
      create: true
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$2
        path: /thanos(/|$)(.*)
        enabled: true
        ingressClassName: nginx
    extraScrapeConfigs: |
      - job_name: 'prometheus-nginx-ingress'
        metrics_path: /metrics
        static_configs:
          - targets:
            - ingress-nginx-controller-metrics.cluster-tools.svc.cluster.local
        kubernetes_sd_configs:
          - role: endpoints
        scrape_interval: 1m
        scrape_timeout: 30s