kube-prometheus:
  prometheus:
    thanos:
      create: true
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /
        path: /thanos
        enabled: true
        ingressClassName: nginx