kube-prometheus:
  prometheus:
    persistence:
      enabled: true
      storageClass: nfs-client
    ingress:
      enabled: true
      ingressClassName: nginx
      path: /prometheus(/|$)(.*)
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
    thanos:
      create: true
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$2
        path: /thanos(/|$)(.*)
        enabled: true
        ingressClassName: nginx
  alertManager:
    persistence:
      enabled: true
      storageClass: nfs-client
