scrape_secrets:
  enabled: false
  name: ''

kube-prometheus:
  prometheus:
    retention: 3d
    remoteWrite:
      - url: https://mimir.mattgerega.net/api/v1/push
    persistence:
      enabled: true
      storageClass: nfs-client
    ingress:
      enabled: true
      ingressClassName: nginx
      path: /prometheus(/|$)(.*)
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
    thanos:
      create: false
  alertmanager:
    enabled: false
    persistence:
      enabled: true
      storageClass: nfs-client
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      path: /alertmanager(/|$)(.*)
      ingressClassName: nginx
