{{- if .Values.internal_scrape_config.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.internal_scrape_config.name }}-es
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.internal_scrape_config.name }}
    template:
      engineVersion: v2
      data:
        scrape-jobs.yaml: |
          - job_name: minio-job
            bearer_token:  {{`"{{ .token }}"`}}
            metrics_path: /minio/v2/metrics/cluster
            scheme: http
            static_configs:
            - targets: ['cloud.gerega.net:39000']
          - job_name: 'vault-job'
            metrics_path: "/v1/sys/metrics"
            params:
              format: ['prometheus']
            scheme: https
            bearer_token: {{`"{{ .metric_token }}"`}}
            static_configs:
            - targets: ['hcvault.mattgerega.net']
          - job_name: 'windows-exporter-job'
            metrics_path: "/metrics"
            scheme: http
            static_configs:
            - targets: [ {{ {{ .windows-targets }} }} ]
  data:
  - secretKey: token
    remoteRef:
      key: secrets-k8/monitoring/minio
      property: authtoken
  - secretKey: metric_token
    remoteRef:
      key: secrets-k8/monitoring/vault
      property: metric-token
  - secretKey: windows_targets
    remoteRef:
      key: secrets-k8/monitoring/targets
      property: windows-targets
{{- end }}