{{- if .Values.production_scrape_config.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.production_scrape_config.name }}-es
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.production_scrape_config.name }}
    template:
      engineVersion: v2
      data:
        scrape-jobs.yaml: |
          - job_name: "hass"
            scrape_interval: 60s
            metrics_path: /api/prometheus

            # Long-Lived Access Token
            authorization:
              credentials: {{`"{{ .hasstoken }}"`}}

            scheme: http
            static_configs:
              - targets: ['home-assistant:8123']
  data:
  - secretKey: hasstoken
    remoteRef:
      key: secrets-k8/hass
      property: token
{{- end }}