{{- if .Values.scrape_secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.scrape_secrets.name }}-es
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.scrape_secrets.name }}
    template:
      engineVersion: v2
      data:
        scrape-jobs.yaml: |
          - job_name: minio-job
            bearer_token:  {{`"{{ .token }}"`}}
            metrics_path: /minio/v2/metrics/cluster
            scheme: http
            static_configs:
            - targets: ['minio.gerega.net:9000']
          - job_name: 'vault-job'
            metrics_path: "/v1/sys/metrics"
            params:
              format: ['prometheus']
            scheme: https
            bearer_token: {{`"{{ .metric-token }}"`}}
            static_configs:
            - targets: ['vault.mattgerega.net']
  data:
  - secretKey: token
    remoteRef:
      key: secrets-k8/monitoring/minio
      property: authtoken
  - secretKey: metric-token
    remoteRef:
      key: secrets-k8/monitoring/vault
      property: metric-token
{{- end }}