apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-application-sets
  labels:
    spydersoft.io/environment: non-production
    spydersoft.io/category: app
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: argocd
  source:
    path: applicationSets
    repoURL: https://bitbucket.org/spydersoftteam/ops-prod-cluster
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true