apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home-automation-apps-prod
  labels:
    environment: production
    category: app
spec:
  generators:
  - git:
      repoURL: https://bitbucket.org/spydersoftteam/ops-prod-cluster
      revision: HEAD
      directories:
      - path: apps/production/*
  template:
    metadata:
      name: '{{path.basename}}-{{path[1]}}'
      labels:
        environment: production
        category: app
    spec:
      project: home-automation
      source:
        repoURL: https://bitbucket.org/spydersoftteam/ops-prod-cluster
        targetRevision: main
        path: '{{ path }}'
        directory:
          recurse: true
      destination:
        server: https://192.168.1.46:6443
        namespace: '{{ path[1] }}'
      