loki-distributed:
  gateway:
    ingress:
      hosts:
        - host: "prod-cluster.mattgerega.net"
          paths:
            - path: /loki
              pathType: Prefix
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /
  loki:
    structuredConfig:
        aws:
          s3: http://${MINIO_USERNAME}:${MINIO_PASSWORD}@192.168.1.46:9000/loki-production
