apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.mattgerega.net"
      path: "secrets-k8"
      version: "v2"
      auth:
        # VaultAppRole authenticates with Vault using the
        # App Role auth mechanism
        # https://www.vaultproject.io/docs/auth/approle
        appRole:
          # Path where the App Role authentication backend is mounted
          path: "approle"
          # RoleID configured in the App Role authentication backend
          roleId: "ff783514-0540-c011-61d6-770d12d31597"
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: "k8-app-role-secret"
            namespace: external-secrets
            key: "secret-id"
